// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw2H_4v7Yb1DWuXmztHZ8pWqYjZKvJJJk',
    appId: '1:844508327926:web:614df6c52efc02be4aa1d7',
    messagingSenderId: '844508327926',
    projectId: 'konne-e976f',
    authDomain: 'konne-e976f.firebaseapp.com',
    storageBucket: 'konne-e976f.appspot.com',
    measurementId: 'G-9NJY81KVD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkDAcOBEYA4VdUu9cIH5elWqyQuS9zTL0',
    appId: '1:844508327926:android:141866a53bfd18954aa1d7',
    messagingSenderId: '844508327926',
    projectId: 'konne-e976f',
    storageBucket: 'konne-e976f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOqY_EMskHf1Iy0V0V_-PLxl6MfWtOqVg',
    appId: '1:844508327926:ios:89c1baa6e326d5c74aa1d7',
    messagingSenderId: '844508327926',
    projectId: 'konne-e976f',
    storageBucket: 'konne-e976f.appspot.com',
    iosBundleId: 'com.example.konneSp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOqY_EMskHf1Iy0V0V_-PLxl6MfWtOqVg',
    appId: '1:844508327926:ios:b8d29be76b293c144aa1d7',
    messagingSenderId: '844508327926',
    projectId: 'konne-e976f',
    storageBucket: 'konne-e976f.appspot.com',
    iosBundleId: 'com.example.konneSp.RunnerTests',
  );
}
